import { useEffect, useState } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { supabase } from '../lib/supabase';
import { useAuth } from '../contexts/AuthContext';
import { useLanguage } from '../contexts/LanguageContext';
import { formatCurrency, formatDate, formatDateTime } from '../lib/helpers';
import { ArrowLeft, Download, Printer } from 'lucide-react';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

interface SaleDetail {
  id: string;
  customer_id: string;
  total_amount: number;
  amount_paid: number;
  payment_method: string | null;
  sale_date: string;
  invoice_number: string | null;
  notes: string | null;
  created_at: string;
  customers: { name: string; mobile: string; address: string | null } | null;
  sale_items: {
    id: string;
    material_id: string;
    quantity: number;
    unit_price: number;
    total_price: number;
    materials: { name: string; unit: string } | null;
  }[];
}

export default function InvoicePage() {
  const { id } = useParams();
  const { user } = useAuth();
  const { t } = useLanguage();
  const navigate = useNavigate();
  const [sale, setSale] = useState<SaleDetail | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (user && id) loadSale();
  }, [user, id]);

  const loadSale = async () => {
    const { data } = await supabase
      .from('sales')
      .select('*, customers(name, mobile, address), sale_items(id, material_id, quantity, unit_price, total_price, materials(name, unit))')
      .eq('id', id)
      .single();
    if (data) setSale(data as SaleDetail);
    setLoading(false);
  };

  const downloadPdf = () => {
    if (!sale) return;
    const doc = new jsPDF();

    // Header
    doc.setFontSize(22);
    doc.setFont('helvetica', 'bold');
    doc.text('INVOICE', 14, 20);

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100);
    doc.text(t('appName'), 14, 28);
    doc.setTextColor(0);

    // Invoice details
    doc.setFontSize(10);
    doc.text(`${t('invoiceNo')}: ${sale.invoice_number || '-'}`, 140, 20);
    doc.text(`${t('date')}: ${formatDate(sale.sale_date)}`, 140, 26);
    doc.text(`${t('paymentMethod')}: ${(sale.payment_method || '-').replace('_', ' ').toUpperCase()}`, 140, 32);

    // Customer info
    doc.setDrawColor(200);
    doc.line(14, 38, 196, 38);
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.text(t('billTo'), 14, 46);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    if (sale.customers) {
      doc.text(sale.customers.name, 14, 52);
      doc.text(`${t('phone')}: ${sale.customers.mobile}`, 14, 58);
      if (sale.customers.address) doc.text(sale.customers.address, 14, 64);
    }

    // Items table
    const tableData = sale.sale_items.map((item, idx) => [
      idx + 1,
      item.materials?.name || '-',
      `${item.quantity} ${item.materials?.unit || ''}`,
      formatCurrency(item.unit_price),
      formatCurrency(item.total_price),
    ]);

    autoTable(doc, {
      startY: 72,
      head: [['#', t('item'), t('quantity'), t('unitPrice'), t('totalAmount')]],
      body: tableData,
      theme: 'striped',
      headStyles: { fillColor: [37, 99, 235], textColor: 255, fontStyle: 'bold' },
      styles: { fontSize: 9, cellPadding: 4 },
      columnStyles: {
        0: { cellWidth: 12 },
        3: { halign: 'right' },
        4: { halign: 'right' },
      },
    });

    const finalY = (doc as any).lastAutoTable.finalY + 10;

    // Totals
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.text(`${t('subtotal')}:`, 140, finalY);
    doc.text(formatCurrency(sale.total_amount), 190, finalY, { align: 'right' });

    doc.setFont('helvetica', 'normal');
    doc.setTextColor(22, 163, 74);
    doc.text(`${t('paid')}:`, 140, finalY + 8);
    doc.text(formatCurrency(sale.amount_paid), 190, finalY + 8, { align: 'right' });

    const due = Number(sale.total_amount) - Number(sale.amount_paid);
    if (due > 0) {
      doc.setTextColor(220, 38, 38);
      doc.setFont('helvetica', 'bold');
      doc.text(`${t('due')}:`, 140, finalY + 16);
      doc.text(formatCurrency(due), 190, finalY + 16, { align: 'right' });
    }

    doc.setTextColor(0);
    doc.setDrawColor(200);
    doc.line(14, finalY + 24, 196, finalY + 24);

    doc.setFontSize(8);
    doc.setTextColor(120);
    doc.text(`Generated by ${t('appName')} on ${formatDateTime(new Date())}`, 14, finalY + 30);

    doc.save(`Invoice-${sale.invoice_number || id}.pdf`);
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center h-64">
        <div className="animate-spin w-8 h-8 border-2 border-blue-600 border-t-transparent rounded-full" />
      </div>
    );
  }

  if (!sale) {
    return (
      <div className="text-center py-12">
        <p className="text-slate-500">{t('noData')}</p>
        <button onClick={() => navigate('/sales')} className="mt-3 text-blue-600 text-sm font-medium">{t('back')}</button>
      </div>
    );
  }

  const due = Number(sale.total_amount) - Number(sale.amount_paid);

  return (
    <div className="max-w-3xl mx-auto space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <button onClick={() => navigate('/sales')} className="flex items-center gap-2 text-slate-600 hover:text-slate-800 text-sm">
          <ArrowLeft size={18} />
          {t('back')}
        </button>
        <div className="flex gap-2">
          <button onClick={() => window.print()} className="flex items-center gap-2 bg-slate-100 text-slate-700 px-4 py-2 rounded-lg text-sm font-medium hover:bg-slate-200 transition-colors">
            <Printer size={16} />
            {t('print')}
          </button>
          <button onClick={downloadPdf} className="flex items-center gap-2 bg-blue-600 text-white px-4 py-2 rounded-lg text-sm font-medium hover:bg-blue-700 transition-colors">
            <Download size={16} />
            {t('downloadPdf')}
          </button>
        </div>
      </div>

      {/* Invoice Card */}
      <div className="bg-white rounded-2xl border border-slate-200 shadow-sm overflow-hidden print:shadow-none print:border-0">
        {/* Invoice header */}
        <div className="bg-slate-800 text-white p-6 print:bg-slate-800">
          <div className="flex justify-between items-start">
            <div>
              <h1 className="text-2xl font-bold">{t('invoice')}</h1>
              <p className="text-slate-300 text-sm mt-1">{t('appName')}</p>
            </div>
            <div className="text-right">
              <p className="text-sm text-slate-300">{t('invoiceNo')}</p>
              <p className="font-mono font-bold">{sale.invoice_number || '-'}</p>
              <p className="text-sm text-slate-300 mt-1">{formatDate(sale.sale_date)}</p>
            </div>
          </div>
        </div>

        {/* Customer info */}
        <div className="p-6 border-b border-slate-200">
          <p className="text-xs text-slate-400 uppercase tracking-wider font-medium mb-2">{t('billTo')}</p>
          {sale.customers && (
            <div>
              <p className="text-lg font-semibold text-slate-800">{sale.customers.name}</p>
              <p className="text-sm text-slate-500">{t('phone')}: {sale.customers.mobile}</p>
              {sale.customers.address && <p className="text-sm text-slate-500">{sale.customers.address}</p>}
            </div>
          )}
        </div>

        {/* Items */}
        <div className="p-6">
          <table className="w-full text-sm">
            <thead>
              <tr className="border-b border-slate-200">
                <th className="text-left py-3 text-slate-600 font-medium">#</th>
                <th className="text-left py-3 text-slate-600 font-medium">{t('item')}</th>
                <th className="text-right py-3 text-slate-600 font-medium">{t('quantity')}</th>
                <th className="text-right py-3 text-slate-600 font-medium">{t('unitPrice')}</th>
                <th className="text-right py-3 text-slate-600 font-medium">{t('totalAmount')}</th>
              </tr>
            </thead>
            <tbody>
              {sale.sale_items.map((item, idx) => (
                <tr key={item.id} className="border-b border-slate-100">
                  <td className="py-3 text-slate-700">{idx + 1}</td>
                  <td className="py-3 text-slate-700 font-medium">{item.materials?.name || '-'}</td>
                  <td className="py-3 text-slate-700 text-right">{item.quantity} {item.materials?.unit || ''}</td>
                  <td className="py-3 text-slate-700 text-right">{formatCurrency(item.unit_price)}</td>
                  <td className="py-3 text-slate-700 text-right font-medium">{formatCurrency(item.total_price)}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        {/* Totals */}
        <div className="p-6 bg-slate-50">
          <div className="flex justify-end">
            <div className="w-64 space-y-2">
              <div className="flex justify-between text-sm">
                <span className="text-slate-600">{t('subtotal')}</span>
                <span className="font-bold text-slate-800">{formatCurrency(sale.total_amount)}</span>
              </div>
              <div className="flex justify-between text-sm">
                <span className="text-emerald-600">{t('paid')}</span>
                <span className="font-medium text-emerald-600">{formatCurrency(sale.amount_paid)}</span>
              </div>
              {due > 0 && (
                <div className="flex justify-between text-sm pt-2 border-t border-slate-200">
                  <span className="text-red-600 font-medium">{t('due')}</span>
                  <span className="font-bold text-red-600">{formatCurrency(due)}</span>
                </div>
              )}
              {due <= 0 && (
                <div className="flex justify-between text-sm pt-2 border-t border-slate-200">
                  <span className="text-emerald-600 font-medium">PAID IN FULL</span>
                  <span className="font-bold text-emerald-600">0.00</span>
                </div>
              )}
            </div>
          </div>
        </div>

        {/* Payment method & notes */}
        <div className="p-6 border-t border-slate-200 text-xs text-slate-400">
          <p>{t('paymentMethod')}: {(sale.payment_method || '-').replace('_', ' ').toUpperCase()}</p>
          {sale.notes && <p>{t('notes')}: {sale.notes}</p>}
        </div>
      </div>
    </div>
  );
}
